# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=13)),
                ('receiver', models.CharField(max_length=13)),
                ('raw', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
    ]
